---
version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis:/data

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "bwoa", "-d", "bwoa_development"]
      interval: 10s
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/dumps/:/docker-entrypoint-initdb.d/

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: MINIO
      MINIO_ROOT_PASSWORD: PASSWORD
      MINIO_VOLUMES: /data
    command: server /data/ --console-address ":9001"
    volumes:
      - minio:/data
    ports:
      - 9000
      - 9001

volumes:
  redis:
  db:
  minio:
