#!/bin/sh

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --show-toplevel`"
git ls-files | ctags --tag-relative -L - -f"$dir/$$.tags" #--languages=-javascript,sql
mv "$dir/$$.tags" "$dir/.tags"
